url: https://github.com/projectcalico/calico/releases/download/v3.22.2/tigera-operator-v3.22.2.tgz
packageVersion: 04
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
